import type { Machine, KPIs } from './types';

/** Zeroed placeholder until the first live webhook payload arrives. */
export const WAITING_MACHINE: Machine = {
  machineId: '—',
  machineName: 'Waiting for API…',
  timestamp: '',
  date: undefined,
  time: undefined,
  kw: 0,
  current: 0,
  voltage: 0,
  powerFactor: 0,
  normalKw: 0,
  deviation: 0,
  temp: 0,
  humidite: 0,
  pression: 0,
  costPerHour: 0,
  tarifKwh: 0,
  trancheHoraire: '—',
  conseilTarif: undefined,
  co2ParHeure: 0,
  co2ParJour: 0,
  co2Economise: 0,
  scoreUsure: 0,
  prochaineMaintenance: '—',
  driftPct: 0,
  driftAlerte: false,
  driftMessage: undefined,
  horsProduction: undefined,
  isAnomaly: false,
  anomalyType: '—',
  severity: 'NORMAL',
  scenario: '—',
  status: 'NOMINAL',
  anomaly: false,
  cause: undefined,
  wifi_rssi: 0,
  relay: false,
  cooldown_remaining: null,
};

export const EMPTY_KPIS: KPIs = {
  coutEvite: 0,
  tempsDetection: 0,
  anomaliesSemaine: 0,
  tauxFaussesAlertes: 0,
  disponibiliteFlotte: 0,
  co2Evite: 0,
  scoreUsureMoyen: 0,
};
